### ISSUE TITLE
creating files in same folder?

### ISSUE THREAD

**Issue by unmenschlich** [dezem/SAK#8]
at the moment, when i create nsz file from nsp SAK create it under SAK\squirrel\ and move it than under the SAK\\.
why not creating it direct or on finished move to same folder where nsp file is?

**Comment by dezem** [comment]
i would say -> it's by design 😄

For each included tool, which is not from me.
I use a own different temp dir to keep it clean (for me).
e.g. squirrel, 4nxci and co.
And ya at the end all files will be moved to the root dir.

The only exception is the XCI/NSP split function.
Here you can directly split to a USB device.
